create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null,
  excerpt text not null,
  content text not null,
  category text not null check (category in ('Personal Finance', 'Mutual Funds', 'SIP & Investing', 'Financial Planning', 'Wealth Protection', 'Investing Basics')),
  featured boolean not null default false,
  published boolean not null default false,
  published_at timestamptz,
  meta_title text,
  meta_description text,
  focus_keyword text,
  canonical_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.articles enable row level security;

create index if not exists articles_published_category_idx
  on public.articles (published, category, published_at desc);

comment on table public.articles is
  'Moneze Learn CMS. Published articles appear automatically on /learn.';
