import { useState } from "react";

const descriptions = { page_view: "A visitor opened a page", session_start: "A new visit started", first_visit: "A visitor arrived for the first time", user_engagement: "A visitor actively engaged with the site", begin_consultation: "The consultation flow was opened", otp_sent: "A verification code was requested", contact_verified: "Contact verification completed", consultation_scheduled: "A Calendly booking was completed", generate_lead: "A financial assessment was submitted", form_submit: "A form was submitted", scroll: "A visitor reached the GA4 scroll milestone", ui_click: "A website control was clicked (earlier tracking)", scroll_depth: "A scroll milestone was reached (earlier tracking)" };
const describe = (name) => name.startsWith("click_") ? `Clicked “${name.slice(6).replaceAll("_", " ")}”` : /^scroll_depth_\d+$/.test(name) ? `Reached ${name.split("_").at(-1)}% of the page` : descriptions[name] || name.replaceAll("_", " ");
const pageLabel = (page) => { try { const url = new URL(page); return `${url.pathname}${url.hash}` || "/"; } catch { return page || "Page unavailable"; } };

export default function AdminEngagement({ data }) {
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const rows = (data.activity || []).filter((row) => (filter === "all" || (filter === "clicks" ? row.name.startsWith("click_") || row.name === "ui_click" : row.name.startsWith("scroll"))) && `${describe(row.name)} ${pageLabel(row.page)}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <section className="admin-ga-pages"><div><p>YOUR VISITORS</p><h2>Where visitors come from</h2></div><p>Anonymous visitor groups by city, country, device and acquisition source. User counts can overlap across groups.</p><div>{data.visitors?.map((row, index) => <article key={index}><span>{row.city}, {row.country}<small>{row.device} · {row.channel}</small></span><strong>{row.users} users</strong><small>{row.sessions} visits</small></article>)}</div>{!data.visitors?.length && <p className="admin-ga-empty">Visitor details appear after GA4 processes activity.</p>}</section>
    <section className="admin-ga-pages"><div><p>WEBSITE ACTIVITY</p><h2>What happened and where</h2></div><p>Click counts are interactions; scroll counts show how often visitors reached each page-depth milestone. These are aggregate reports, not session recordings.</p><div className="admin-activity-controls"><select aria-label="Activity type" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All events</option><option value="clicks">Clicks</option><option value="scrolls">Scroll depth</option></select><input aria-label="Search website activity" placeholder="Search action or page" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="admin-activity-list">{rows.map((row, index) => <article key={index}><span>{describe(row.name)}<small title={row.page}>{pageLabel(row.page)}</small></span><strong>{row.count} events</strong><small>{row.users} users</small></article>)}</div>{!rows.length && <p className="admin-ga-empty">No matching activity yet. Detailed button labels and scroll percentages start with this update.</p>}</section>
    <section className="admin-ga-pages"><div><p>EVENT TOTALS</p><h2>All recorded website events</h2></div><div>{data.events?.map((event) => <article key={event.name}><span>{describe(event.name)}<small>{event.name}</small></span><strong>{event.count.toLocaleString("en-IN")}</strong></article>)}</div></section>
  </>;
}
